Feat/create why we do it on client
citi-onboarding/Eventos-CITi pull request #12
Opened 2020-12-03 17:32 UTC by Monterazo

## What I did

- Create the Why We Do It component
- Create the global css file 
- Add background-color and limit horizontal overflow

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. git checkout develop
   1. git pull
   1. git checkout feat/create-why-we-do-it-on-client
   1. git pull origin feat/create-why-we-do-it-on-client
   1. cd server/
   1. node index.js

1. Open another terminal at the folder of this projects
  
1. In terminal
    1. cd client/
    1. npm run start

1. At localhost:3000
    1. Check if the content is aligned as in [https://www.figma.com/file/2UJF2r572kDAU4snBxUMwx/citi-eventos?node-id=0%3A1](url)
   1. Try to swipe to the sides to check if there's no overflow
   1. Toggle device emulation after pressing ctrl +shift + i
   1.  Check width 375px

2020-12-03 20:55 UTC, guilhermefxs approved these changes

2020-12-04 01:39 UTC, viniciusscala requested changes
- The bubble is being cut in the bottom

- The color of the text is different from the mockup

2020-12-04 02:17 UTC, Monterazo commented
> * The bubble is being cut in the bottom
> * The color of the text is different from the mockup
> * The margin between the title and the text is bigger in the mockup

* Bubble being cut is not an issue, it will be shown correctly as the other components are inserted
* Collor corrected
* Margins fixed

2020-12-04 02:41 UTC, viniciusscala approved these changes
Everything is perfect!

2020-12-04 10:16 UTC, merged