Feat/create banner
citi-onboarding/Eventos-CITi pull request #13
Opened 2020-12-03 18:48 UTC by raissaheimann

## What I did
1. Create a banner on the site
2. Put two bubbles(blue and green)

## How to test
Open the terminal and go to the folder of this project
In terminal type:
i. git checkout develop
ii. git pull
iii. git checkout feat/create-banner
iv. git pull origin feat/create-why-we-do-it-on-client
v. cd server/
vi. node index.js

Open another terminal at the folder of this projects and type:
i. cd client/
ii. npm run start

In your browser:
1. Open localhost http://localhost:3000
2. See if is similiar to the mockup
3. Open the mockup https://www.figma.com/file/2UJF2r572kDAU4snBxUMwx/citi-eventos?node-id=69%3A0
4. Check if the sizes are responsive for desktop and mobile

2020-12-03 23:36 UTC, Monterazo submitted a review, later dismissed
The mobile subtitle is not aligned with the title, the top end bubbles are not aligned with the right corners and the 1920px+  style is missing

2020-12-04 01:31 UTC, viniciusscala requested changes
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/41218597/101110119-173b9480-35b7-11eb-9473-88bfa9d5f7f1.png">
 - The blue bouble in the right is on top of the illustration
 - The website is not responsive, if we are in a phone resolution, it will have a horizontal scroll, and if we are in a resolution bigger than 1920, ite breaks
 - The text has no style in the mobile version

2020-12-11 18:10 UTC, viniciusscala requested changes, later dismissed
<img width="132" alt="image" src="https://user-images.githubusercontent.com/41218597/101938877-e5cc5580-3bc2-11eb-9845-4aa4df941cbd.png">

in 320px of width, a little of the tittle is being cut

2020-12-12 05:13 UTC, guilhermefxs approved these changes

2020-12-12 06:48 UTC, merged