Feat/create our events section
citi-onboarding/Eventos-CITi pull request #14
Opened 2020-12-09 05:00 UTC by guilhermefxs

## What I did

- Create Our Events Section
   - create a react slick carousel to our events, which are events that already happend with cards

- Create a function that gets events and separate between our events and agenda

<img src="https://user-images.githubusercontent.com/42884185/101587003-efd33600-39c1-11eb-9eb5-2ad10808f639.png" />

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal, open 3 tabs:
    1. Tab 1:
       1. `git checkout develop`
       1. `git pull`
       1. `git checkout feat/create-our-events-section
       1. `git pull origin feat/create-our-events-section
    1. Tab 2:
       1. `cd server`
       1. `npm install`
       1. `npm run start`
    1. Tab 3:
       1. `cd client`
       1. `node index.js`

1. In your browser go to http://localhost:3000 and http://localhost:3001/admin

1. Check if the component looks just like the mockup in the erspective widths
    1. 3000px (Larger than usual - Margin has to grow and the content stay in the middle)
    1. 1920px (large web - Has to be axactly equals to me mockup)
    1. 1600px (usual web - the content has to fit the screen without breaking)
    1. 1025px (Smallest web - the content has to fit the screen without breaking)
    1. 1024px (Biggest mobile - the content has to fit the screen without breaking)
    1. 600px (Usual mobile - the content has to fit the screen without breaking)
    1. 320px (Smallest mobile - the content has to fit the screen without breaking)
    
1. In the admin page, try to edit something relative to this issue and check if it updates in the front

1. Read the changed files section on GitHub and check if the code is okay

1. Test the things that you think are worth testing, even the ones that are not in this description

2020-12-10 14:54 UTC, Monterazo requested changes
It works fine, but you could fix the shadows by deleting the .ourEventsCard div margin and by adding 25px to the bottom margin and 12px for left and right margin. Also, the description font-weight should be switched to 401, so the color is the same as in the mockup and the cards get too tall in bigger screens

2020-12-10 14:54 UTC, Monterazo commented on client/src/components/OurEvents/OurEvents.jsx
> +    <section className="our-events">
Needs to have an id so the navbar can find this section

2020-12-11 13:27 UTC, Monterazo approved these changes
All fixed, working fine!

2020-12-11 16:56 UTC, raissaheimann approved these changes
Everything is perfect after you changed the things Monterazzo asked you for. Congrats :)

2020-12-11 17:21 UTC, merged