Feat/create events model
citi-onboarding/Eventos-CITi pull request #7
Opened 2020-11-27 21:25 UTC by raissaheimann

## What I did

- Create events.js on models 
- Create all the columns about events:
1. name
2. date
3. images
4. description
5. link
6. simpledescription

## How to test

1. Open the http://localhost:3001/admin
2. Open events and create a event
3. Put a name and hold create
4. Put the other informations(date, images, description, link and simple description)
5. Press create and that's it :)

2020-11-27 22:22 UTC, viniciusscala requested changes

2020-11-27 22:22 UTC, viniciusscala commented on server/models/Post.js
> +    type: Types.CloudinaryImage,
This will probably break the front end

2020-11-27 22:24 UTC, viniciusscala requested changes
The name of the models file should start with a uppercase latter

2020-11-27 22:54 UTC, viniciusscala approved these changes
Perfect 😁

2020-11-30 22:46 UTC, Monterazo requested changes
Command node index.js doesn't work and sends the following error:

Error: Invalid Configuration

Field (Events.images) is required but not initial, and has no default or generat
ed value.
Please provide a default, remove the required setting, or set initial: false to
override this error.

2020-11-30 23:30 UTC, Monterazo approved these changes
It seems ok!

2020-11-30 23:31 UTC, guilhermefxs approved these changes

2020-11-30 23:31 UTC, guilhermefxs commented on server/models/Post.js
> +    type: Types.CloudinaryImage,
This will probably break the front end, don't take the 's' off of Types.CloudinaryImages

2020-11-30 23:39 UTC, merged