Feat/create blog model
citi-onboarding/Eventos-CITi pull request #8
Opened 2020-11-27 21:31 UTC by Monterazo

## What I did

- Create Blog.js file inside models folder at server
- Insert the source /api/blogpost at index.js
-

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. cd server/
   1. node index.js
  
1. In your browser
   1. Open localhost [http://localhost:3001/admin/blog-posts](url)
   1.  Then press Blog Post
   1. Check if image, date, description and link fields are available
   1. Then, save the model
   1. Go back to [http://localhost:3001/admin/blog-posts](url)
   1. Check if the blog archive has the correct title (id)
   1. Go to [http://localhost:3001/api/blogpost](url)
   1. Check if error 500 is not showing up
   1. Check if the code is showing up

&nbsp;
*

2020-11-27 22:35 UTC, viniciusscala requested changes
Try to make everything required

2020-11-27 22:35 UTC, viniciusscala commented on server/models/Blog.js
> +
Erase this blank line

2020-11-27 22:35 UTC, viniciusscala commented on server/models/Blog.js
> +  description: {
I think it's better to change this name to content, since this is the beggining of the blog post

2020-11-27 23:01 UTC, guilhermefxs reviewed
Everything looks good

2020-11-30 23:16 UTC, guilhermefxs approved these changes

2020-11-30 23:16 UTC, raissaheimann commented on server/models/Post.js
> +    type: Types.CloudinaryImage,
Put the "s" because this will probably break the front end

2020-11-30 23:17 UTC, raissaheimann approved these changes

2020-11-30 23:20 UTC, viniciusscala approved these changes

2020-11-30 23:22 UTC, merged